# Generated by Django 2.1.1 on 2018-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional_language',
            name='language_id',
        ),
        migrations.RemoveField(
            model_name='profesional_language',
            name='profesional_id',
        ),
        migrations.AddField(
            model_name='language',
            name='profesionals',
            field=models.ManyToManyField(related_name='language', related_query_name='language', to='Profesionals.profesional'),
        ),
        migrations.AlterField(
            model_name='language_tips',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='profesional_language',
        ),
    ]
