# Generated by Django 2.1.1 on 2018-09-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0002_auto_20180904_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesional_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='profesionals',
            field=models.ManyToManyField(related_name='language', related_query_name='language', to='Profesionals.profesional_language'),
        ),
        migrations.AddField(
            model_name='profesional_language',
            name='group',
            field=models.ManyToManyField(related_name='profesional_language', related_query_name='profesional_language', to='Profesionals.language'),
        ),
    ]
