# Generated by Django 2.1.1 on 2018-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0003_auto_20180904_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional_language',
            name='group',
        ),
        migrations.RemoveField(
            model_name='language',
            name='profesionals',
        ),
        migrations.AddField(
            model_name='profesional',
            name='languages',
            field=models.ManyToManyField(to='Profesionals.language'),
        ),
        migrations.DeleteModel(
            name='profesional_language',
        ),
    ]
