# Generated by Django 2.1.1 on 2018-09-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0004_auto_20180904_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='languages',
        ),
    ]
