# Generated by Django 2.1.1 on 2018-09-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0005_remove_profesional_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='languages',
            field=models.ManyToManyField(to='Profesionals.language'),
        ),
    ]
