# Generated by Django 2.1.1 on 2018-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionals', '0006_profesional_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language_tips',
            name='language_id',
        ),
        migrations.AddField(
            model_name='language_tips',
            name='language_id',
            field=models.ManyToManyField(to='Profesionals.language'),
        ),
    ]
